# Generated by Django 3.0.7 on 2020-07-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200708_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='createUser',
            new_name='createdUser',
        ),
    ]
