# Generated by Django 3.0.7 on 2020-07-09 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200708_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listingID',
        ),
    ]
