# Generated by Django 3.0.7 on 2020-07-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200709_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='userBid',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userBid',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='userBid',
            new_name='username',
        ),
    ]
