# Generated by Django 3.0.7 on 2020-07-10 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200709_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listingID',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listingID',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingID',
            new_name='listing',
        ),
    ]
