# Generated by Django 3.0.7 on 2020-07-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200710_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchFlag',
            field=models.BooleanField(default=False),
        ),
    ]
