# Generated by Django 3.0.7 on 2020-07-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_listing_watchflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
