# Generated by Django 3.0.7 on 2020-07-11 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20200711_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='currentBid',
            new_name='initialBid',
        ),
    ]
