# Generated by Django 3.0.7 on 2020-07-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20200711_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidAmount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
